image: node:latest

before_script:
  - npm ci

stages:
  - check
  - test
  - db
  - production

check:
  only:
    - master
  script:
    - npm run lint
  stage: check

db:
  only:
    - master
  script:
    - npm run db
  stage: db
  variables:
    NODE_ENV: production

test:
  only:
    - master
  script:
    - npm t
  stage: test

production:
  before_script: []
  image: ruby:latest
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  stage: production
  variables:
    NODE_ENV: production
