FROM node:erbium

ARG MY_INSTAGRAM_API_DATABASE_HOST
ARG MY_INSTAGRAM_API_DATABASE_NAME
ARG MY_INSTAGRAM_API_DATABASE_PASSWORD
ARG MY_INSTAGRAM_API_DATABASE_USER
ARG NODE_ENV

WORKDIR /www/api

COPY package*.json ./

RUN npm ci --silent

COPY . .

EXPOSE 8080

CMD ["npm", "start"]
