module.exports = {
    assignActivationCodeForUser: require('./assignActivationCodeForUser'),
    checkCodeAndEmail: require('./checkCodeAndEmail'),
    checkEmailHasCode: require('./checkEmailHasCode'),
    checkPasswordAndConfirmAreEquals: require('./checkPasswordAndConfirmAreEquals'),
    confirmSignUp: require('./confirmSignUp'),
    createActivationCode: require('./createActivationCode'),
    existsEmail: require('./existsEmail'),
    existsUsername: require('./existsUsername'),
    resendCode: require('./resendCode'),
    sendConfirmSignUpEmail: require('./sendConfirmSignUpEmail'),
    sendResendCodeEmail: require('./sendResendCodeEmail'),
    sendSignInEmail: require('./sendSignInEmail'),
    sendSignUpEmail: require('./sendSignUpEmail'),
    signIn: require('./signIn'),
    signUp: require('./signUp'),
}
